// <auto-generated />
using System;
using InventarioWEB.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventarioWEB.Migrations
{
    [DbContext(typeof(TenantDbContext))]
    [Migration("20260809002523_InicialTenant")]
    partial class InicialTenant
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("InventarioWEB.Models.Abono", b =>
                {
                    b.Property<int>("ID_Abono")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID_Abono"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Fecha_Abono")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ID_MetodoPago")
                        .HasColumnType("int");

                    b.Property<int>("ID_Pedido")
                        .HasColumnType("int");

                    b.Property<int?>("ID_Usuario")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("NumeroRecibo")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Observacion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RutaRecibo")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("UsuarioRegistro")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("ID_Abono");

                    b.HasIndex("ID_MetodoPago");

                    b.HasIndex("ID_Pedido");

                    b.ToTable("abono", (string)null);
                });

            modelBuilder.Entity("InventarioWEB.Models.Cliente", b =>
                {
                    b.Property<int>("ID_Cliente")
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CiudadMunicipio")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("HashContrasena")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("TipoCliente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("VIP")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("ID_Cliente");

                    b.HasIndex("TipoCliente");

                    b.ToTable("cliente", (string)null);
                });

            modelBuilder.Entity("InventarioWEB.Models.Color", b =>
                {
                    b.Property<int>("ID_Color")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID_Color"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("ID_Color");

                    b.ToTable("colores", (string)null);
                });

            modelBuilder.Entity("InventarioWEB.Models.CorreoEnviado", b =>
                {
                    b.Property<int>("IdCorreo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCorreo"));

                    b.Property<string>("Destinatario")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ID_Pedido")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("IdCorreo");

                    b.HasIndex("ID_Pedido");

                    b.ToTable("correo_enviado");
                });

            modelBuilder.Entity("InventarioWEB.Models.Despacho", b =>
                {
                    b.Property<int>("ID_Despacho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID_Despacho"));

                    b.Property<string>("CorreoDestino")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("CorreoEnviado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaEnvioCorreo")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ID_Pedido")
                        .HasColumnType("int")
                        .HasColumnName("ID_Pedido");

                    b.Property<string>("Observacion")
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UsuarioEnvioCorreo")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("ID_Despacho");

                    b.HasIndex("ID_Pedido");

                    b.ToTable("despacho", (string)null);
                });

            modelBuilder.Entity("InventarioWEB.Models.DetalleDespacho", b =>
                {
                    b.Property<int>("ID_DetalleDespacho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_DetalleDespacho");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID_DetalleDespacho"));

                    b.Property<int>("Cantidad_Despachada")
                        .HasColumnType("int");

                    b.Property<int>("ID_Despacho")
                        .HasColumnType("int");

                    b.Property<int>("ID_Detalle")
                        .HasColumnType("int")
                        .HasColumnName("ID_Detalle");

                    b.Property<int?>("ID_Detalle_Produccion")
                        .HasColumnType("int");

                    b.Property<int>("ID_Producto")
                        .HasColumnType("int");

                    b.HasKey("ID_DetalleDespacho");

                    b.HasIndex("ID_Detalle");

                    b.HasIndex("ID_Detalle_Produccion");

                    b.HasIndex("ID_Producto");

                    b.HasIndex("ID_Despacho", "ID_Detalle")
                        .IsUnique();

                    b.ToTable("detalle_despacho", (string)null);
                });

            modelBuilder.Entity("InventarioWEB.Models.DetallePedido", b =>
                {
                    b.Property<int>("ID_Detalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Detalle");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID_Detalle"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("Cantidad");

                    b.Property<int>("ID_Pedido")
                        .HasColumnType("int")
                        .HasColumnName("ID_Pedido");

                    b.Property<int>("ID_Producto")
                        .HasColumnType("int")
                        .HasColumnName("ID_Producto");

                    b.Property<decimal>("IVA_Porcentaje")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("IVA_Porcentaje");

                    b.Property<decimal>("IVA_Valor")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("IVA_Valor");

                    b.Property<decimal>("PrecioBase")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("PrecioBase");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("PrecioVenta");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Subtotal");

                    b.HasKey("ID_Detalle");

                    b.HasIndex("ID_Producto");

                    b.HasIndex("ID_Pedido", "ID_Producto")
                        .IsUnique();

                    b.ToTable("detalle_pedido", (string)null);
                });

            modelBuilder.Entity("InventarioWEB.Models.DetalleProduccion", b =>
                {
                    b.Property<int>("ID_DetalleProduccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Detalle_Produccion");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID_DetalleProduccion"));

                    b.Property<int>("CantidadProducida")
                        .HasColumnType("int")
                        .HasColumnName("CantidadProducida");

                    b.Property<decimal>("CostoUnitario")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("EstadoProduccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("FechaFinProduccion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaInicioProduccion")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ID_DetallePedido")
                        .HasColumnType("int")
                        .HasColumnName("ID_DetallePedido");

                    b.Property<int>("ID_Produccion")
                        .HasColumnType("int")
                        .HasColumnName("ID_Produccion");

                    b.Property<int>("ID_Producto")
                        .HasColumnType("int")
                        .HasColumnName("ID_Producto");

                    b.Property<decimal>("IVA")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("ObservacionProduccion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("PrecioVentaUnitario")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("SubtotalCosto")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("SubtotalVenta")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("ID_DetalleProduccion");

                    b.HasIndex("ID_DetallePedido");

                    b.HasIndex("ID_Produccion");

                    b.HasIndex("ID_Producto");

                    b.ToTable("detalle_produccion", (string)null);
                });

            modelBuilder.Entity("InventarioWEB.Models.EnvioWhatsApp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdClienteNavigationID_Cliente")
                        .HasColumnType("int");

                    b.Property<int>("IdPedido")
                        .HasColumnType("int");

                    b.Property<int>("IdPedidoNavigationID_Pedido")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UrlPdf")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IdClienteNavigationID_Cliente");

                    b.HasIndex("IdPedidoNavigationID_Pedido");

                    b.ToTable("EnvioWhatsApp");
                });

            modelBuilder.Entity("InventarioWEB.Models.Genero", b =>
                {
                    b.Property<int>("ID_Genero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID_Genero"));

                    b.Property<string>("DescripGenero")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("ID_Genero");

                    b.ToTable("genero", (string)null);
                });

            modelBuilder.Entity("InventarioWEB.Models.HistorialInventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Cliente")
                        .HasColumnType("longtext");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("DespachoId")
                        .HasColumnType("int");

                    b.Property<string>("DocumentoReferencia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdGenero")
                        .HasColumnType("int");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Observaciones")
                        .HasColumnType("longtext");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StockActual")
                        .HasColumnType("int");

                    b.Property<int>("StockAnterior")
                        .HasColumnType("int");

                    b.Property<string>("Talla")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tela")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioNombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("VentaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("historialinventario");
                });

            modelBuilder.Entity("InventarioWEB.Models.MetodoPago", b =>
                {
                    b.Property<int>("ID_MetodoPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID_MetodoPago"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Categoria")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("ID_MetodoPago");

                    b.ToTable("metodopago", (string)null);
                });

            modelBuilder.Entity("InventarioWEB.Models.MovimientoInventario", b =>
                {
                    b.Property<int>("ID_Movimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID_Movimiento"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ID_Origen")
                        .HasColumnType("int");

                    b.Property<int>("ID_Producto")
                        .HasColumnType("int");

                    b.Property<string>("Observacion")
                        .HasColumnType("longtext");

                    b.Property<string>("TablaOrigen")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Usuario")
                        .HasColumnType("longtext");

                    b.HasKey("ID_Movimiento");

                    b.HasIndex("ID_Producto");

                    b.ToTable("movimiento_inventario", (string)null);
                });

            modelBuilder.Entity("InventarioWEB.Models.PasswordResetCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiraToken")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ID_Cliente")
                        .HasColumnType("int")
                        .HasColumnName("ID_Cliente");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Usado")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("ID_Cliente");

                    b.ToTable("passwordresetsclientes", (string)null);
                });

            modelBuilder.Entity("InventarioWEB.Models.Pedido", b =>
                {
                    b.Property<int>("ID_Pedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID_Pedido"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("EstadoPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ID_Cliente")
                        .HasColumnType("int");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("TipoVenta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TotalIVA")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("TotalIVA");

                    b.Property<decimal>("TotalVenta")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("ID_Pedido");

                    b.HasIndex("ID_Cliente");

                    b.ToTable("pedido", (string)null);
                });

            modelBuilder.Entity("InventarioWEB.Models.Produccion", b =>
                {
                    b.Property<int>("ID_Produccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Produccion");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID_Produccion"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Activo");

                    b.Property<DateTime>("FechaProduccion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("FechaProduccion");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("FechaRegistro");

                    b.Property<string>("Observacion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Observacion");

                    b.Property<string>("Usuario")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Usuario");

                    b.HasKey("ID_Produccion");

                    b.HasIndex("Activo", "FechaProduccion")
                        .HasDatabaseName("idx_produccion_fecha");

                    b.ToTable("produccion", (string)null);
                });

            modelBuilder.Entity("InventarioWEB.Models.Producto", b =>
                {
                    b.Property<int>("ID_Producto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Producto");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID_Producto"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Activo");

                    b.Property<string>("ColorSnapshot")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("Color");

                    b.Property<int>("ID_Color")
                        .HasColumnType("int")
                        .HasColumnName("ID_Color");

                    b.Property<int>("ID_Genero")
                        .HasColumnType("int")
                        .HasColumnName("ID_Genero");

                    b.Property<int>("ID_Referencias")
                        .HasColumnType("int")
                        .HasColumnName("ID_Referencias");

                    b.Property<int>("ID_Tallas")
                        .HasColumnType("int")
                        .HasColumnName("ID_Tallas");

                    b.Property<int>("ID_Telas")
                        .HasColumnType("int")
                        .HasColumnName("ID_Telas");

                    b.Property<decimal>("IVA_Porcentaje")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("IVA_Porcentaje");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("Nombre");

                    b.Property<decimal>("PrecioCosto")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("PrecioCosto");

                    b.Property<decimal>("PrecioVTA")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("PrecioVTA");

                    b.Property<int>("Stock")
                        .HasColumnType("int")
                        .HasColumnName("Stock");

                    b.HasKey("ID_Producto");

                    b.HasIndex("ID_Color");

                    b.HasIndex("ID_Genero");

                    b.HasIndex("ID_Tallas");

                    b.HasIndex("ID_Telas");

                    b.HasIndex("ID_Referencias", "ID_Tallas", "ID_Telas", "ID_Color", "Activo")
                        .HasDatabaseName("idx_producto_busqueda_real");

                    b.ToTable("productos", (string)null);
                });

            modelBuilder.Entity("InventarioWEB.Models.Referencia", b =>
                {
                    b.Property<int>("ID_Referencias")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID_Referencias"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("DescripReferencia")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("ID_Genero")
                        .HasColumnType("int");

                    b.HasKey("ID_Referencias");

                    b.HasIndex("ID_Genero");

                    b.ToTable("referencias", (string)null);
                });

            modelBuilder.Entity("InventarioWEB.Models.ReferenciaTela", b =>
                {
                    b.Property<int>("ID_Referencias")
                        .HasColumnType("int");

                    b.Property<int>("ID_Tallas")
                        .HasColumnType("int");

                    b.Property<int>("ID_Telas")
                        .HasColumnType("int");

                    b.Property<int?>("GeneroID_Genero")
                        .HasColumnType("int");

                    b.Property<int>("ReferenciaID_Referencias")
                        .HasColumnType("int");

                    b.Property<int>("TallaID_Tallas")
                        .HasColumnType("int");

                    b.Property<int>("TelaID_Telas")
                        .HasColumnType("int");

                    b.HasKey("ID_Referencias", "ID_Tallas", "ID_Telas");

                    b.HasIndex("GeneroID_Genero");

                    b.HasIndex("ReferenciaID_Referencias");

                    b.HasIndex("TallaID_Tallas");

                    b.HasIndex("TelaID_Telas");

                    b.ToTable("referencias_telas", (string)null);
                });

            modelBuilder.Entity("InventarioWEB.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdRol");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("InventarioWEB.Models.Tela", b =>
                {
                    b.Property<int>("ID_Telas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID_Telas"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("DescripTela")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("ID_Telas");

                    b.ToTable("telas", (string)null);
                });

            modelBuilder.Entity("InventarioWEB.Models.TipoCliente", b =>
                {
                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Nombre");

                    b.ToTable("tipocliente", (string)null);
                });

            modelBuilder.Entity("InventarioWEB.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaUltimaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("HashContrasena")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdRol");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("Talla", b =>
                {
                    b.Property<int>("ID_Tallas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID_Tallas"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("DescripTalla")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("ID_Genero")
                        .HasColumnType("int");

                    b.HasKey("ID_Tallas");

                    b.HasIndex("ID_Genero");

                    b.ToTable("tallas", (string)null);
                });

            modelBuilder.Entity("InventarioWEB.Models.Abono", b =>
                {
                    b.HasOne("InventarioWEB.Models.MetodoPago", "MetodoPago")
                        .WithMany("Abonos")
                        .HasForeignKey("ID_MetodoPago")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InventarioWEB.Models.Pedido", "Pedido")
                        .WithMany("Abonos")
                        .HasForeignKey("ID_Pedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MetodoPago");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("InventarioWEB.Models.Cliente", b =>
                {
                    b.HasOne("InventarioWEB.Models.TipoCliente", "TipoClienteNav")
                        .WithMany()
                        .HasForeignKey("TipoCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoClienteNav");
                });

            modelBuilder.Entity("InventarioWEB.Models.CorreoEnviado", b =>
                {
                    b.HasOne("InventarioWEB.Models.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("ID_Pedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("InventarioWEB.Models.Despacho", b =>
                {
                    b.HasOne("InventarioWEB.Models.Pedido", "Pedido")
                        .WithMany("Despachos")
                        .HasForeignKey("ID_Pedido")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("InventarioWEB.Models.DetalleDespacho", b =>
                {
                    b.HasOne("InventarioWEB.Models.Despacho", "Despacho")
                        .WithMany("Detalles")
                        .HasForeignKey("ID_Despacho")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventarioWEB.Models.DetallePedido", "DetallePedido")
                        .WithMany()
                        .HasForeignKey("ID_Detalle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventarioWEB.Models.DetalleProduccion", "DetalleProduccion")
                        .WithMany()
                        .HasForeignKey("ID_Detalle_Produccion");

                    b.HasOne("InventarioWEB.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ID_Producto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Despacho");

                    b.Navigation("DetallePedido");

                    b.Navigation("DetalleProduccion");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("InventarioWEB.Models.DetallePedido", b =>
                {
                    b.HasOne("InventarioWEB.Models.Pedido", "Pedido")
                        .WithMany("DetallePedidos")
                        .HasForeignKey("ID_Pedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventarioWEB.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ID_Producto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("InventarioWEB.Models.DetalleProduccion", b =>
                {
                    b.HasOne("InventarioWEB.Models.DetallePedido", "DetallePedido")
                        .WithMany()
                        .HasForeignKey("ID_DetallePedido");

                    b.HasOne("InventarioWEB.Models.Produccion", "Produccion")
                        .WithMany("Detalles")
                        .HasForeignKey("ID_Produccion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventarioWEB.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ID_Producto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DetallePedido");

                    b.Navigation("Produccion");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("InventarioWEB.Models.EnvioWhatsApp", b =>
                {
                    b.HasOne("InventarioWEB.Models.Cliente", "IdClienteNavigation")
                        .WithMany()
                        .HasForeignKey("IdClienteNavigationID_Cliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventarioWEB.Models.Pedido", "IdPedidoNavigation")
                        .WithMany()
                        .HasForeignKey("IdPedidoNavigationID_Pedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdPedidoNavigation");
                });

            modelBuilder.Entity("InventarioWEB.Models.MovimientoInventario", b =>
                {
                    b.HasOne("InventarioWEB.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ID_Producto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("InventarioWEB.Models.PasswordResetCliente", b =>
                {
                    b.HasOne("InventarioWEB.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ID_Cliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("InventarioWEB.Models.Pedido", b =>
                {
                    b.HasOne("InventarioWEB.Models.Cliente", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("ID_Cliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("InventarioWEB.Models.Producto", b =>
                {
                    b.HasOne("InventarioWEB.Models.Color", "ColorNav")
                        .WithMany("Productos")
                        .HasForeignKey("ID_Color")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InventarioWEB.Models.Genero", "Genero")
                        .WithMany()
                        .HasForeignKey("ID_Genero")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventarioWEB.Models.Referencia", "Referencia")
                        .WithMany()
                        .HasForeignKey("ID_Referencias")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Talla", "Talla")
                        .WithMany()
                        .HasForeignKey("ID_Tallas")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InventarioWEB.Models.Tela", "Tela")
                        .WithMany()
                        .HasForeignKey("ID_Telas")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ColorNav");

                    b.Navigation("Genero");

                    b.Navigation("Referencia");

                    b.Navigation("Talla");

                    b.Navigation("Tela");
                });

            modelBuilder.Entity("InventarioWEB.Models.Referencia", b =>
                {
                    b.HasOne("InventarioWEB.Models.Genero", "Genero")
                        .WithMany("Referencias")
                        .HasForeignKey("ID_Genero")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Genero");
                });

            modelBuilder.Entity("InventarioWEB.Models.ReferenciaTela", b =>
                {
                    b.HasOne("InventarioWEB.Models.Genero", null)
                        .WithMany("ReferenciasTelas")
                        .HasForeignKey("GeneroID_Genero");

                    b.HasOne("InventarioWEB.Models.Referencia", "Referencia")
                        .WithMany()
                        .HasForeignKey("ReferenciaID_Referencias")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Talla", "Talla")
                        .WithMany()
                        .HasForeignKey("TallaID_Tallas")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventarioWEB.Models.Tela", "Tela")
                        .WithMany("ReferenciasTelas")
                        .HasForeignKey("TelaID_Telas")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Referencia");

                    b.Navigation("Talla");

                    b.Navigation("Tela");
                });

            modelBuilder.Entity("InventarioWEB.Models.Usuario", b =>
                {
                    b.HasOne("InventarioWEB.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Talla", b =>
                {
                    b.HasOne("InventarioWEB.Models.Genero", "Genero")
                        .WithMany("Tallas")
                        .HasForeignKey("ID_Genero")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Genero");
                });

            modelBuilder.Entity("InventarioWEB.Models.Cliente", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("InventarioWEB.Models.Color", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("InventarioWEB.Models.Despacho", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("InventarioWEB.Models.Genero", b =>
                {
                    b.Navigation("Referencias");

                    b.Navigation("ReferenciasTelas");

                    b.Navigation("Tallas");
                });

            modelBuilder.Entity("InventarioWEB.Models.MetodoPago", b =>
                {
                    b.Navigation("Abonos");
                });

            modelBuilder.Entity("InventarioWEB.Models.Pedido", b =>
                {
                    b.Navigation("Abonos");

                    b.Navigation("Despachos");

                    b.Navigation("DetallePedidos");
                });

            modelBuilder.Entity("InventarioWEB.Models.Produccion", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("InventarioWEB.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("InventarioWEB.Models.Tela", b =>
                {
                    b.Navigation("ReferenciasTelas");
                });
#pragma warning restore 612, 618
        }
    }
}
